### ISSUE TITLE
Why is observing state on mainThread not supported in 2.1.0 release?

### ISSUE THREAD

**Issue by sanichdaniel** [ReactorKit/ReactorKit#149]
Before 2.1.0 release, `state` was observed on mainThread, but now it is not certain.
This causes crashes on places where I assumed state is observed from mainThread.

I see `scheduler` property, but `scheduler` observes on `action` stream. So if thread changes at `mutate()`or `transform()`, it will override `scheduler` stream. 

Is it possible to rollback to the days when `state` was guaranteed to be  delivered from mainThread? 
Or could there be a way to fix this problem?
Thank you

**Comment by smajdalf** [comment]
Hi, as you may see. In version 2.1.0 the `.observeOn(MainScheduler.instance)` was removed from `Reactor.swift` file. It ensured that obtained state change was populated on main thread. 

It means, that you need to handle the scheduler before you bind value to UI. For example:
`reactor.state.map { $0.isValid }.observeOn(MainScheduler.instance).subscribe { ... }` or you can you `reactor.state.map { $0.isValid }.drive { ... }` which will automatically observe value on MainScheduler.

And why did it change? I think it's because before you were forced to observe changes on main thread, and right now it's up to you and your decision.

**Comment by sanichdaniel** [comment]
> @sanichdaniel Hi, as you may see. In version 2.1.0 the `.observeOn(MainScheduler.instance)` was removed from `Reactor.swift` file. It ensured that obtained state change was populated on main thread.
> 
> It means, that you need to handle the scheduler before you bind value to UI. For example:
> `reactor.state.map { $0.isValid }.observeOn(MainScheduler.instance).subscribe { ... }` or you can use `reactor.state.map { $0.isValid }.drive { ... }` which will automatically observe value on MainScheduler.
> 
> And why did it change? I think it's because before you were forced to observe changes on main thread, and right now it's up to you and your decision.

@smajdalf Hi. 
There are tons of codes where I assumed state is observed from mainThread. It will take too much time and effort to put `observeOn(MainScheduler.instance).subscribe { ... } ` or `reactor.state.map { $0.isValid }.drive { ... }` everywhere.
So I think I will stick to 2.0.0 release for now.
Thank you for your answer. :)

**Comment by devxoul** [comment]
Hi, since 2.1.0 the default scheduler is changed to `CurrentThreadScheduler`. It means that if the bindings are made in a non-main thread, the reactor states will be observed in that thread. If there are too many locations to fix, you may specify the scheduler:

```swift
class MyReactor {
  let scheduler: Scheduler = MainScheduler.instance
}
```

Also I have updated the release note to inform about the breaking API changes.

Thanks!

**Comment by sanichdaniel** [comment]
@devxoul Hi. 
In my case, I made bindings to non-main thread inside `mutate()`. 
So even if I specify scheduler as `MainScheduler`,
It would not help, since scheduler observes on `action` stream and `state` will be delivered by the latest thread from `mutate`

So I was thinking of using `transform(state:` to observe mainThread.  
Thank you!

**Comment by devxoul** [comment]
This is definitely unintended behavior. #152 is a patch that ensures the states be always observed on the given scheduler. I'm going to test on a production environment and will make a new release soon. Sorry for inconvenience :pray:

**Comment by sanichdaniel** [comment]
@devxoul 
Hi, thanks for the new patch 🙏 
I have a question for this new patch.

I use mainScheduler to send actions for User Interactions and another non-main Scheduler to send actions for expensive nonUI works(that slows down UI if ran on mainThread). 
But after the new patch if I specify mainScheduler as my scheduler property (since I want to observe states on mainThread) automatically all the actions would also be observed on mainThread too.
Since expensive works are sent through mainThread it would definitely clog mainThread. 
So I think enforcing action to be observed on only 1 scheduler is only causing constraints.

The reason why you made scheduler to observe action and state is too guarantee `mutate() and reduce() are performed in the difference scheduler to ensure order of executions`.
But even if this specified scheduler observes action and state, it would not guarantee `mutate` and `reduce` is performed on same thread since threads could change in `mutate`.

So if I may suggest, wouldn't it be better if scheduler property only observes on state?

Thank you!
