### ISSUE TITLE
Why state is observable, not a Driver?

### ISSUE THREAD

**Issue by MortyMerr** [ReactorKit/ReactorKit#71]
Correct me if i'm wrong, but using `Driver` seems to be more logical and relevant due to RxSwift best practices.

**Comment by devxoul** [comment]
ReactorKit aims to support not only UI stuffs but also logical stuffs. `Driver` enforces to use main thread only so I used `Observable` instead. You could still use `reactor.state.asDriver()`.

**Comment by kimballAtLive** [comment]
@sunlyear Yes I believe it does, and I don't believe it should for precisely the reason @devxoul mentioned. We should be able to observe `state` on any thread without having to route it through the main thread so that we can use it for more than just driving `UIKit`.

Also consider [Texture](https://github.com/TextureGroup/Texture) which is designed to handle most UI updates on a background thread. Forcing the observables through the main thread creates a bottleneck and could potentially undo the performance improvements granted by such frameworks.

In practice, switching immediately back to another thread with `reactor.state.observeOn(...)` would probably mean there's little difference, but that's kind of a nuisance.

**Comment by MortyMerr** [comment]
I am fulfilled with these answers, thank you :)
